[default]
extend-ignore-re = ["(?Rm)^.*(#|//)\\s*spellchecker:disable-line$"]

[default.extend-identifiers]
iNdEx = "iNdEx"
typ = "typ"

[files]
extend-exclude = ["**/go.mod", "**/go.sum", "**/*.pb.go"]
